version: "3.8"
services:
  npm-app:
    hostname: npm-app
    container_name: npm-app  
    image: jc21/nginx-proxy-manager:2.11.2
    restart: unless-stopped
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
#      - "21:21" # FTP
    environment:
      DISABLE_IPV6: "true"
      DB_MYSQL_HOST: $MYSQL_HOST
      DB_MYSQL_PORT: $MYSQL_PORT
      DB_MYSQL_USER: $MYSQL_USER
      DB_MYSQL_PASSWORD: $MYSQL_PASS
      DB_MYSQL_NAME: $MYSQL_DB      
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M        
    networks:
      - npm-network
      - default            
    depends_on:
      - npm-db

  npm-db:
    hostname: npm-db
    container_name: npm-db    
    image: jc21/mariadb-aria:10.11.5-innodb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - ./mysql:/var/lib/mysql        
    networks:
      - default        

networks:
  npm-network:
    name: npm-network
    external: true